esphome:
  name: test-device
  friendly_name: Test Device

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # level: NONE
  # level: ERROR
  # level: WARN
  # level: INFO
  level: DEBUG # default
  # level: VERBOSE
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# for wesp32 board rev.7 and up
# @see https://esphome.io/components/ethernet.html#configuration-examples
ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 0
  phy_registers:
    - address: 0x10
      value: 0x1FFA
      page_id: 0x07

external_components:
  - source:
      # type: git
      # url: https://github.com/antokara/esphome-fswm100
      # ref: test-1
      type: local
      path: ./esphome/components
    components: [fswm100]
    refresh: 0.5min

# demo with fsw100
fswm100:
  ads1115_id: ads1115_a
  flow:
    name: Water Flow
    unit_of_measurement: gal/min
    accuracy_decimals: 2
    # in GPM
    min_volume: 0.07
    max_volume: 15.0
    rate_time: 60.0
    # multiplier applied to the time between pulses
    # to determine if the flow rate should be re-calculated
    # and avoid spikes in the flow rate.
    # this adds buffer time between pulses before
    # recalculating the flow rate.
    flow_rate_time_between_pulses_multiplier: 1.25
    # The multiplier applied to the time since last activity
    # to determine if the IR sensor is faulty (stuck on active),
    # when there is a pulse sensor toggle.
    fault_time_since_flow_ir_activity_multiplier: 3.0
    # the number of IR inactivity faults that must happen
    # in a row, to consider the IR sensor as faulty
    inactivity_fault_counter_threshold: 3
    filters:
      # this does not apply during the start/stop of flow
      - delta: 0.5
      - heartbeat: 20s
  flow_ir:
    name: Water Flow IR Sensor
    # in volts
    #  effective_noise_floor: 0.0009-0.022 idle
    #  effective_noise_floor: 0.0300-0.120 flow
    effective_noise_floor: 0.05
    min_voltage: 2.0
    max_voltage: 3.4
    # The interval in milliseconds to publish the debug state meta information
    # of the flow sensor.
    debug_publish_interval_ms: 30000
    # ADS1115
    multiplexer: "A0_GND"
    gain: 6.144
    sample_rate: 860
    resolution: 16_BITS
    # prevent excessive toggling of the sensor
    # (just for reporting purposes. it does not affect flow detection)
    filters:
      - delayed_off: 10sec
  pulse:
    name: Water Meter Pulse
    rate_volume: 1
    # The multiplier applied to the flow time out period
    # to determine if the pulse sensor is faulty
    # (has not toggled for too long).
    fault_flow_timeout_multiplier: 1.5
    # the number of pulse inactivity faults that must happen
    # in a row, to consider the pulse sensor as faulty
    inactivity_fault_counter_threshold: 3
    gpio_pin:
      number: GPIO23
      mode:
        input: true
    filters:
      - delayed_off: 250ms
  pressure:
    name: Water Pressure
    accuracy_decimals: 2
    unit_of_measurement: psi
    min_voltage: 0.5
    max_voltage: 5
    min_pressure: 0
    max_pressure: 100
    # the expected pressure drop percentage
    # when there is flow, to be cosnsidered normal
    # if that does not happen, a fault count is registered
    flow_correlation_drop_perc: 5.0
    # the number to multiply the flow_sensor_min_duration by
    # in order to get the diagnostics window for the
    # flow/pressure correlation.
    # the higher the number, the less false positives
    flow_correlation_window_multiplier: 3.0
    # the number of correlation faults that must happen
    # within the diagnostics window (gte),
    # to consider the pressure sensor as faulty
    flow_correlation_fault_counter_threshold: 5
    # in volts
    effective_noise_floor: 0.1
    # ADS1115
    multiplexer: "A1_GND"
    gain: 6.144
    sample_rate: 860
    resolution: 16_BITS
    filters:
      # this does not apply during the start/stop
      # of the pressure test
      - delta: 1
  pressure_test:
    name: Water Pressure Test
    accuracy_decimals: 2
    filters:
      # these do not apply during the start/stop
      # of the pressure test
      - exponential_moving_average:
          alpha: 0.0005
          send_every: 10
      - delta: 0.01
  status_led:
    red:
      number: GPIO18
    green:
      number: GPIO05
    blue:
      number: GPIO32
    
# required (shared) component by fsw100
i2c:
  id: i2c_a
  sda: GPIO15
  scl: GPIO04
  scan: true
  frequency: 100kHz

# required (shared) component by fsw100
ads1115:
  id: ads1115_a
  i2c_id: i2c_a
  address: 0x48
  # important. must be set to false
  continuous_mode: false
